name: har-detector-evaluation
type: evaluation
dataset:
  name: MIOT-2020Q4-relabeled-test
  path: /data/sensor-data/activity-recognition/ailab/clean/cleaned-0628-test-ailab-converted
algos:
  har_model:
    module: activity-recognition.src.py.har_model
    name: HarModel
metric:
  har_model_metric:
    module: metrics.har.har_metrics
    name: HarModelStreamMetric
