name: har-detector-evaluation
type: evaluation
dataset:
  name: MIOT-2020Q4-relabeled-test
  path: https://cnbj1.fds.api.xiaomi.com/new-sensor-bucket/sensor-data/activity-recognition/clean/MIOT-2020Q4-relabeled-test.zip
  sha256sum: 4b949a3de6f029d5153d4ecd5e49ef68f7fb50e8284a66270258bec520368aa0
algos:
  har_detector:
    module: activity-recognition.src.py.har_det
    name: HarDetector
pre_algos:
  har_model:
    module: activity-recognition.src.py.har_model
    name: HarModel
metric:
  har_det_metric:
    module: metrics.har.har_metrics
    name: HarDetMetric
