name: har-detector-evaluation
type: evaluation
dataset:
  name: MIOT-2020Q4-relabeled-test
  path: /data/sensor-data/activity-recognition/miot/clean/MIOT-2020Q4-relabeled-test
algos:
  har_detector:
    module: activity-recognition.src.py.har_det
    name: HarDetector
pre_algos:
  har_model:
    module: activity-recognition.src.py.har_model
    name: HarModelCNN
metric:
  har_det_metric:
    module: metrics.har.har_metrics
    name: HarDetMetric
